<a href="https://colab.research.google.com/github/ankit-singh973/Deep_Learning/blob/main/1_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Fundamentals**


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [5]:
!nvidia-smi

Sat Oct 28 06:47:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## **Introduction to Tensors**

### **Create Tensors**
> PyTorch tensors are created using `torch.Tensor()`

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

- A scalar has no dimensions

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
vector = torch.Tensor([7, 7])
vector

tensor([7., 7.])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# Matrix
MATRIX = torch.Tensor([[7, 8],
                      [5, 6]])
MATRIX

tensor([[7., 8.],
        [5., 6.]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[1]

tensor([5., 6.])

In [16]:
# TENSOR
TENSOR = torch.Tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])
TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 6.]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1., 2., 3.],
        [3., 6., 9.],
        [2., 4., 6.]])

### Random Tensors

Why random Tensors?
> Random tensors are important because the way many neural netwirks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [20]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3523, 0.1276, 0.8817, 0.2034],
        [0.2786, 0.2937, 0.0258, 0.9611],
        [0.1998, 0.3982, 0.8859, 0.1547]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
random_tensor1 = torch.rand([5, 3, 4])
random_tensor1

tensor([[[0.4785, 0.9073, 0.7491, 0.9605],
         [0.9097, 0.9623, 0.0856, 0.3546],
         [0.1589, 0.7290, 0.7169, 0.4446]],

        [[0.1798, 0.1377, 0.1872, 0.4828],
         [0.3740, 0.3197, 0.4925, 0.1951],
         [0.4388, 0.4406, 0.9250, 0.0645]],

        [[0.8043, 0.5259, 0.7227, 0.8002],
         [0.6239, 0.8209, 0.1086, 0.3121],
         [0.7696, 0.3032, 0.8838, 0.4090]],

        [[0.3818, 0.4314, 0.5857, 0.6332],
         [0.6503, 0.7966, 0.4831, 0.3773],
         [0.6319, 0.5362, 0.3416, 0.9822]],

        [[0.4733, 0.4329, 0.2364, 0.5957],
         [0.1895, 0.2918, 0.3717, 0.4606],
         [0.0067, 0.6071, 0.6337, 0.4899]]])

In [24]:
random_tensor1.ndim

3

In [25]:
random_tensor1.shape

torch.Size([5, 3, 4])

In [26]:
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, w idth color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## **Zeros and Ones**

In [27]:
# create tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# multiply two tensors
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

## **Create a range of tensors**

In [31]:
# use torch.arange(start, end, step)
one_to_ten = torch.arange(0, 100, 5)
one_to_ten

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [32]:
 # creating tensor like
ten_zeros = torch.zeros_like(input =  one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Tensor Datatypes**

**Note:**  Tensor datatypes is one of the 3 big errors with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float32, #hwat datatype is tenosr
                               device = None, # what device is your tensor on
                               requires_grad = False) # wether to track gradients with this tensor operation
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
# converting float32 to float16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
aas =  float_16_tensor*float_32_tensor
aas

tensor([ 9., 36., 81.])

In [37]:
aas.dtype

torch.float32

In [38]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9519, 0.9386, 0.1520, 0.1978],
        [0.6088, 0.3815, 0.9902, 0.0390],
        [0.5616, 0.4468, 0.4435, 0.5441]])

In [39]:
# find out details about some_tensor
print(some_tensor,'\n')
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape} ")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9519, 0.9386, 0.1520, 0.1978],
        [0.6088, 0.3815, 0.9902, 0.0390],
        [0.5616, 0.4468, 0.4435, 0.5441]]) 

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4]) 
Device tensor is on: cpu


## **Manipulating Tensors (Tensor operations)**

In [40]:
# Create a tensor and add 10 to it
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [41]:
# multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [42]:
# subtract by 10
tensor-10

tensor([-9, -8, -7])

In [43]:
# try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## **Matrix Multiplication (dot product)**
`[2x3] X [3x2] = [2x2]`

In [45]:
# element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [46]:
# PyTorch matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.56 ms, sys: 82 µs, total: 1.64 ms
Wall time: 1.62 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 36 µs, sys: 0 ns, total: 36 µs
Wall time: 38.9 µs


tensor(14)

## **Finding the min, max, mean, sum, etc. (tensor aggregation)**

In [49]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [51]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [52]:
# print the mean.
# The troch.mean requires float and int values only
torch.mean(x.type(torch.float32))

tensor(45.)

In [53]:
# Find the sum
torch.sum(x)

tensor(450)

## **Finding positional min and mx**
`argmin()` and `argmax()`

In [54]:
# position of min value
torch.argmin(x)

tensor(0)

In [55]:
# position of max value
torch.argmax(x)

tensor(9)

## **Reshaping, stacking, squeezing, and unsqueezing**

* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - return view of an input tensor of certain shape but keep the same memory as the original tensor
* **Stacking** - combined multiple tensors on top of each other
* **Squeeze** - removes all one dimensions froma tensors
* **Unsqueeze** - adds  one dimesnion to target tensor
* **Commute** - return a view of input withdimensions permuted(swapped) in a certain way

In [56]:
# Let's create a tensor
x = torch.arange(1., 10.)
print(x,'\n', x.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) 
 torch.Size([9])


In [57]:
# add extra dimensions
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

##**Note:**  changing `z` changes `x` because `view` of a tensor shares memory with the original input

In [59]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [60]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [61]:
y_stacked = torch.stack([x, x, x, x], dim = 1)
y_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [62]:
print(x_reshaped)
print(x_reshaped.shape)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])


In [63]:
# squeeze
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
x_squeezed.shape

torch.Size([9])

In [65]:
#torch.unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed, '\n', x_unsqueezed.shape)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
 torch.Size([1, 9])


## **Indexing (selecting data from tensors)**

In [66]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [67]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
x[0, 0]

tensor([1, 2, 3])

In [69]:
# lets index on middle bracket
x[0, 1]

tensor([4, 5, 6])

In [70]:
x[0,2]

tensor([7, 8, 9])

In [71]:
# you can also use ":" to select "all" of a target dimension
# variable[start:end, column]
x[:, 0]

tensor([[1, 2, 3]])

In [72]:
x[0, 2,2]

tensor(9)

In [73]:
x[:, 1]

tensor([[4, 5, 6]])

In [74]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [75]:
x[:, 1, 1]

tensor([5])

In [76]:
!nvidia-smi

Sat Oct 28 06:47:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [77]:
torch.cuda.is_available()

True

In [79]:
#setup device diagnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

## **Putting tensors (and models) om the GPU**

In [80]:
# create a tensor (default on cpu)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [81]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [82]:
 # moving tensors back to cpu
# if tensor on gpu we can'ttransform it into numpy
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])