<a href="https://colab.research.google.com/github/ankit-singh973/Deep_Learning/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch**

In [ ]:
#pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

In [ ]:
import torch

## **Tensors**

In [ ]:
t1 = torch.tensor(4.)

In [ ]:
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
#vector
t2 = torch.tensor([1.,2.,3.])
t2

tensor([1., 2., 3.])

In [ ]:
t3 = torch.tensor([[5., 6.],
                   [7., 8.],
                   [9., 10.]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
t3.numpy()

array([[ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]], dtype=float32)

In [ ]:
#if we want to check the shape of the tensor `.shape()` is used
print(t1, '\n', t1.shape)
print()
print(t2, '\n', t2.shape)
print()
print(t3, '\n', t3.shape)

tensor(4.) 
 torch.Size([])

tensor([1., 2., 3.]) 
 torch.Size([3])

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) 
 torch.Size([3, 2])


# **Tensor operations and Gradients**

- We can combine tensors with the usual arithmetic operations. Let's look at example


In [ ]:
# create tensors

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = w*x +b
y

tensor(17., grad_fn=<AddBackward0>)

- ### What makes pytorch unique is that we can automatically compute the derivative of `y` w.r.t the tensors that have `requires_grad = True` i.e `w` & `b`.
- This feature of pyorch is called `autograd`(automatic gradients).
- To compute the derivatives, we can invoke the `.backward` method on our result `y`.

In [ ]:
 # Compute derivatives
 y.backward()

- ### The derivatives of `y` with respect to the input tensors are stored in the `.grad` property of respective tensors.

In [ ]:
# display gradients
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ',b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


- As expected, `dy/dw` has the same value as x, i.e 3 and `dy/dw` has the value 1.
- Note that `x.grad` is None because `x` dosen't have `requires_grad` set to `True`.

## **Tensor Functions**

In [ ]:
# create a tensor with fixed value for every tensor
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
# concatenate two tensors with compatible shape
print('shape of t3 is: ',t3.shape, '\n')
print('shape of t6 is: ', t6.shape, '\n')
t7 = torch.cat((t3, t6))
t7

shape of t3 is:  torch.Size([3, 2]) 

shape of t6 is:  torch.Size([3, 2]) 



tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
# compute sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
# change the shape of tensor
t9 = t8.reshape(2, 3, 2)

In [ ]:
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894],
         [ 0.4121, -0.5440]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# **Linear regression using Pytorch**

In [ ]:
import numpy as np

In [ ]:
# making training data
# input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = 'float32')

In [ ]:
# Targets (apples, oranges)
target = np.array([[56, 70],
                   [81, 101],
                   [119, 133],
                   [22, 37],
                   [103, 119]], dtype = 'float32')

In [ ]:
# convert input and target to tensors
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

print(inputs, '\n')
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# weights and biases
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

print(w, '\n')
print(b)

tensor([[-1.1523, -0.6240, -0.7516],
        [ 0.2067,  0.5823,  0.6412]], requires_grad=True) 

tensor([ 1.1364, -0.3363], requires_grad=True)


In [ ]:
# define the model

def model(x):
  return x @ w.t()+b

In [ ]:
# prediction
preds = model(inputs)
print(preds)

tensor([[-157.1075,   81.3393],
        [-206.7361,  110.7537],
        [-226.3199,  132.8638],
        [-171.0400,   69.5127],
        [-190.8863,  114.7112]], grad_fn=<AddBackward0>)


In [ ]:
# actual
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# loss function MSE
def MSE(actul, target):
  diff = actual - target
  return torch.sum(diff * diff) / diff.nume1()

In [ ]:
# error
loss = MSE(target, preds)
print(loss)

In [ ]:
#compute gradient
loss.backward()

In [ ]:
print(w, '\n')
print(w.grad)

In [ ]:
print(b, '\n')
print(b.grad)

In [ ]:
# reset gradients
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

In [ ]:
# adjust params

preds = model(inputs)
print(preds)

In [ ]:
# loss
loss = MSE(target, preds)
print(loss)

In [ ]:
loss.backward()

print(w.grad, '\n')
print(b.grad)

In [ ]:
# adjust weights and reset gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
print(w)
print(b)

## **Neural networks using pytorch**

In [1]:
#to check GPU
!nvidia-smi

Thu Oct 19 09:39:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

In [3]:
# download training data from open datasets
training_data = datasets.FashionMNIST(
    root = 'data',
    train = True,
    download = True,
    transform = ToTensor()
)

# download test data from open datasets
test_data = datasets.FashionMNIST(
    root = 'data',
    train = False,
    download = True,
    transform = ToTensor()
)

100%|██████████| 26421880/26421880 [00:01<00:00, 14217240.20it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 269625.15it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:00<00:00, 5007912.46it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 5865872.59it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [4]:
type(training_data)

torchvision.datasets.mnist.FashionMNIST

In [5]:
# create data loader
batch_size = 64

train_dataloader = DataLoader(training_data, batch_size = batch_size)
test_dataloader = DataLoader(test_data, batch_size = batch_size)

for X,y in test_dataloader:
  print("shape of X [N, C, H, W]: ", X.shape, '\n')
  print("shape of y: ", y.shape, y.dtype, '\n')
  # print (X,'\n')
  # print(y)

  break


shape of X [N, C, H, W]:  torch.Size([64, 1, 28, 28]) 

shape of y:  torch.Size([64]) torch.int64 



In [6]:
# get GPU or CPU device for training
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"using {device} device")

using cuda device


In [7]:
# define model

class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 512),
        nn.ReLU(),
        nn.Linear(512, 512),
        nn.ReLU(),
        nn.Linear(512, 10)
    )

  def forward(self,x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [8]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-1)

In [9]:
# defining train function

def train(dataloader, model, loss_fn, optimizer):
  size = len(dataloader.dataset)
  model.train()
  for batch, (X, y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device)

    # Compute precdiction error
    pred = model(X)
    loss = loss_fn(pred, y)

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100 == 0:
      loss, current = loss.item(), batch *len(X)
      print(f"loss : {loss:>7f} [{current:>5d}/{size:>5d}] ")

In [10]:
def test(dataloader, model, loss_fn):
  size = len(dataloader.dataset)
  num_batches = len(dataloader)
  model.eval()
  test_loss, correct = 0, 0
  with torch.no_grad():
    for X, y in dataloader:
      X, y = X.to(device), y.to(device)
      pred = model(X)
      test_loss += loss_fn(pred, y).item()
      correct += (pred.argmax(1) == y).type(torch.float).sum().item()

  test_loss /= num_batches
  correct /= size
  print(f"Test Error: \n Accuracy : {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [11]:
epochs = 10
for t in range(epochs):
  print(f"Epoch {t+1} \n-----------------------------------")
  train(train_dataloader, model, loss_fn, optimizer)
  test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1 
-----------------------------------
loss : 2.302747 [    0/60000] 
loss : 0.902848 [ 6400/60000] 
loss : 0.569938 [12800/60000] 
loss : 0.695913 [19200/60000] 
loss : 0.591733 [25600/60000] 
loss : 0.511099 [32000/60000] 
loss : 0.543013 [38400/60000] 
loss : 0.581170 [44800/60000] 
loss : 0.619050 [51200/60000] 
loss : 0.449328 [57600/60000] 
Test Error: 
 Accuracy : 79.3%, Avg loss: 0.554454 

Epoch 2 
-----------------------------------
loss : 0.435267 [    0/60000] 
loss : 0.438892 [ 6400/60000] 
loss : 0.373680 [12800/60000] 
loss : 0.443704 [19200/60000] 
loss : 0.413331 [25600/60000] 
loss : 0.449827 [32000/60000] 
loss : 0.402548 [38400/60000] 
loss : 0.495397 [44800/60000] 
loss : 0.508066 [51200/60000] 
loss : 0.419015 [57600/60000] 
Test Error: 
 Accuracy : 82.6%, Avg loss: 0.469033 

Epoch 3 
-----------------------------------
loss : 0.320099 [    0/60000] 
loss : 0.352874 [ 6400/60000] 
loss : 0.308225 [12800/60000] 
loss : 0.370905 [19200/60000] 
loss : 0.346903

In [12]:
# save model
torch.save(model.state_dict(), "model1.pth")
print("Saved PyTorch Model State to model1.pth")

Saved PyTorch Model State to model1.pth


In [13]:
# load model

model = NeuralNetwork()
model.load_state_dict(torch.load("model1.pth"))

<All keys matched successfully>

In [14]:
# Prediction

classes = [
    'T-shirt/top',
    'Trouser',
    'pullover',
    'Dress',
    'Coat',
    'Sandal',
    'Shirt',
    'Sneaker',
    'Bag',
    'Ankle boot'

]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
  pred = model(x)
  predicted, actual = classes[pred[0].argmax(0)], classes[y]
  print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle boot", Actual: "Ankle boot"
