<a href="https://colab.research.google.com/github/ankit-singh973/Deep_Learning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensor Constant:😊**

In [42]:
import tensorflow as tf

In [43]:
x = tf.constant(42)
x

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [44]:
x.numpy()

42

In [45]:
x = tf.constant(1, dtype=tf.int64)
x

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [46]:
x_1 = tf.constant([[4,2], [9,5]])
print(x_1)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [47]:
x_1.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [48]:
print('shape:', x_1.shape)

shape: (2, 2)



*   Commonly used method is to generate `tf.ones` and `tf.zeros` like of numpy `np.ones` and `np.zeros` .



In [49]:
print(tf.ones(shape = (2,3)))


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [50]:
print(tf.zeros(shape = (3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [51]:
const1 = tf.constant([[1,2,3], [4,5,6]])
const2 = tf.constant([[7,8,9], [14, 25, 36]])
result = tf.add(const1, const2)

print(result)

tf.Tensor(
[[ 8 10 12]
 [18 30 42]], shape=(2, 3), dtype=int32)


## **Random constant**

In [52]:
tf.random.normal(shape = (2,2), mean = 0, stddev = 1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.08620322,  0.03173339],
       [ 2.8092692 ,  0.86657816]], dtype=float32)>

In [53]:
tf.random.uniform(shape = (2,2), minval = 0, maxval = 10, dtype = tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 6]], dtype=int32)>

## **Variables**


*   A variable is a special tensor that is used to store variable values and needs to be initialized with some values.



### **Declaring Variables**

In [54]:
var0 = 24  #python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([[0., 1., 2.], [3., 4., 5.], [6., 7., 8.], [9., 10., 11]]) #rank 3 tensor

In [55]:
 var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=float32)>)

## To reassign a variable use `var.assign()`

In [56]:
var4 = tf.Variable(34)
var4

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=34>

In [57]:
var4.assign(69)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=69>

In [58]:
initial_value = tf.random.normal(shape = [2,2])
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.39699882, -0.42931756],
       [-0.30055663,  1.9346113 ]], dtype=float32)>


In [59]:
new_value = tf.random.normal(shape = (2,2))
a.assign(new_value)
for i in range(2):
  for j in range(2):
    assert a[i,j] == new_value[i,j]

In [60]:
added_value = tf.random.normal(shape = (2,2))
a.assign_add(added_value)
for i in range(2):
  for j in range(2):
    assert a[i,j] == new_value[i,j] + added_value[i,j]

In [61]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.25873977, -2.2399402 ],
       [-2.168313  ,  0.42723233]], dtype=float32)>

## **Shaping a tensor**

In [62]:
tensor = tf.Variable([[[0., 1., 2.], [3., 4., 5.]], [[6., 7., 8.], [9., 10., 11]]]) #tensor variable
print(tensor)
print(tensor.shape)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>
(2, 2, 3)


In [63]:
tensor1 = tf.reshape(tensor, [2,6]) # 2 rows & 6 columns
tensor2 = tf.reshape(tensor,[1,12]) # 1 rows & 12 columns
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [64]:
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

## **Ranking (dimension) of a Tensor**


-   The rank of a tensor is the number of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor.


In [65]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

- the shape is () because the output here is  scalar value.

## **Specifying an element of a tensor**

In [66]:
tensor3 = tensor[1, 1, 2] # slice 1, row 1, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=11.0>

## **Casting a tensor to a Numpy/Python variable**

In [67]:
print(tensor.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [68]:
print(tensor[1,0,2].numpy())

8.0


## **Finding the size (number of elements) of a tensor**

In [69]:
tf.size(input = tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [70]:
tf.size(input = tensor).numpy()

12

In [71]:
tensor_size = tf.size(input = tensor).numpy()
tensor_size

12

In [72]:
#the data type of a tensor
tensor3.dtype

tf.float32

# ***Tensorflow Mathematical operations***

- Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.

In [73]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c)
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(e)

tf.Tensor(
[[ 0.2570485   0.21044247]
 [-0.51622444  0.24319836]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[ 0.6272854  -0.435894  ]
 [-1.60293     0.27810168]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[ 0.8843339  -0.22545154]
 [-2.1191545   0.5213001 ]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[0.78204644 0.0508284 ]
 [4.4908156  0.27175376]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[2.421371   0.7981557 ]
 [0.12013316 1.6842158 ]], shape=(2, 2), dtype=float32)


In [74]:
#multiply
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

In [75]:
# subtract
tensor-tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

# **Transpose Matrix multiplication**

In [76]:
matrix_u = tf.constant([[3, 4, 3]])
matrix_v = tf.constant([[1, 2, 1]])

In [77]:
matrix_u

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[3, 4, 3]], dtype=int32)>

In [78]:
matrix_v

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 1]], dtype=int32)>

In [79]:
# for matrix multiplication
# for multiplication the rows and cols must be same, so, we transpose the 2nd matrix
tf.matmul(matrix_u, tf.transpose(a = matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

## **Casting a Tensor to another(tensor) datatype**

In [85]:
i = tf.case(tensor1, dtype = tf.int32)
i

TypeError: ignored

## **Declaring ragged Tensors**

* A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.
* There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array.



The following example shows how to declare a constant ragged array and the lengths of the individual slices:

In [86]:
ragged = tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])

print(ragged)
print(ragged[0, 1])
print(ragged[1, :])
print(ragged[2, :])
print(ragged[3, :])
print(ragged[4, :])


<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


### **Finding squared difference between two tensors**

In [87]:
varx = [1, 3, 5, 7, 11]
vary = 5
varz = tf.math.squared_difference(varx, vary)
print(varz)

tf.Tensor([16  4  0  4 36], shape=(5,), dtype=int32)


## **Finding the Mean**
* the following is the signature of `tf.reduce_mean()`

In [88]:
#Defining a constant
numbers = tf.constant([[4., 5.], [7., 3.]])

In [89]:
#find the mean across all axis
tf.reduce_mean(input_tensor = numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

In [90]:
#find the mean across columns i.e reduce rows
tf.reduce_mean(input_tensor = numbers, axis = 0)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

### When keepdims is True, the reduced axis is retained with a length of 1:

In [91]:
tf.reduce_mean(input_tensor = numbers, axis = 0, keepdims = True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

### Find mean across the rows

In [92]:
tf.reduce_mean(input_tensor = numbers, axis = 1 )

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

In [93]:
tf.reduce_mean(input_tensor = numbers, axis = 1, keepdims = True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

## **Generating tensors filled with random values**

- using `tf.random.normal()`

In [94]:
ran = tf.random.normal(shape = (3,2), mean = 10.0, stddev = 2.0)
print(ran)

tf.Tensor(
[[8.931407  9.751701 ]
 [6.5773287 8.568776 ]
 [9.742659  7.8281083]], shape=(3, 2), dtype=float32)


In [95]:
tf.random.normal(shape = (3,2), mean = 10, stddev = 2, dtype = tf.float32, seed = None, name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 9.359456 ,  6.120927 ],
       [11.6435375, 10.051438 ],
       [12.208949 ,  8.791538 ]], dtype=float32)>

### Using `tf.random.uniform()`

In [96]:
tf.random.uniform(shape = (2,4), minval = 0, maxval = None, dtype = tf.float32, seed = None, name = None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.6251657 , 0.23655677, 0.20135999, 0.5867282 ],
       [0.5490941 , 0.76529396, 0.9623883 , 0.7309669 ]], dtype=float32)>

## **Setting seed**

In [97]:
tf.random.set_seed(11)
ran1 = tf.random.uniform(shape = (2,2), maxval = 10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval = 10, dtype = tf.int32)
print(ran1)
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


## Practical example of Random values using Dices

In [98]:
dice1 = tf.Variable(tf.random.uniform([10,1], minval = 1, maxval = 7, dtype = tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1], minval = 1, maxval = 7, dtype = tf.int32))

#we can add dice1 and dice2 since they share the same and size.
dice_sum = dice1 + dice2

#we've got three separate 10x1 matrices. To produce a single 10x3 matrix, we'll concatenate them along dimension 1.
resulting_matrix = tf.concat(values = [dice1, dice2, dice_sum], axis = 1)
print(resulting_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


### Finding indices of the largest and smallest values

* To find maximum value
  - `tf.argmax(input, axis=None, name=None, output_type= tf.int64)`
* To find minimum value
  - `tf.argmin(input, axis=None, name=None, output_type= tf.int64)`


In [101]:
# 1-D tensor
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
print(t5)

i = tf.argmax(input = t5)
print("index of max: ", i)
print("max element: ", t5[i].numpy())
print()

i = tf.argmin(input = t5)
print("index of min: ", i)
print("min element: ", t5[i].numpy())

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max:  tf.Tensor(3, shape=(), dtype=int64)
max element:  42

index of min:  tf.Tensor(7, shape=(), dtype=int64)
min element:  -11


In [106]:
# for 2-D tensor

t6 = tf.reshape(t5, [3,3])
print(t6)

print()

i = tf.argmax(input = t6, axis = 0).numpy() #max arg down row
print("indices of max down rows: ", i)

print()

i = tf.argmin(input = t6, axis = 0).numpy() #min arg down row
print("indices of min down rows: ", i)

print()

i = tf.argmax(input = t6, axis = 1 ).numpy() #max arg across column
print("indices of max across column: ", i)

print()

i = tf.argmin(input = t6, axis = 1 ).numpy() #min arg across column
print("indices of min across column: ", i)


tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)

indices of max down rows:  [1 0 2]

indices of min down rows:  [2 2 0]

indices of max across column:  [1 0 2]

indices of min across column:  [0 1 1]


## **Saving and restoring Tensor values using a checkpoint**

In [107]:
variable = tf.Variable([[1, 3, 5, 7], [11, 13, 17, 19]])
checkpoint = tf.train.Checkpoint(var = variable)
save_path = checkpoint.save('./vars')
variable.assign([[0, 0, 0, 0], [0, 0, 0, 0]])
variable
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]], dtype=int32)>


## **Using `tf.function()`**

- `tf.function()` is a function that will take a Python function and return a Tensorflow grap.
- The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func).


`tf.function(func = None, input_signature = None, autograph = True, experimental_autograph_options = None)`

In [109]:
def f1(x,y):
  return tf.reduce_mean(input_tensor = tf.multiply(x**2,5)+y**2)

f2 = tf.function(f1)
x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# f1 and f2 return the same value, but f2 execute as a Tensorflow graph
assert f1(x,y).numpy() == f2(x,y).numpy()
#The assert passes, so there is no output

## **Calculate the gradient**

### Gradient Tape

In [111]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))

#it will return differential of c w.r.t a
with tf.GradientTape() as tape:
  tape.watch(a)
  c = tf.sqrt(tf.square(a) + tf.square(b))
  dc_da = tape.gradient(c,a) #differential of c w.r.t a
  print(dc_da)

tf.Tensor(
[[-0.1684204 -0.5020665]
 [ 0.9471321  0.5898169]], shape=(2, 2), dtype=float32)


- ###  *for variables, the calculation is tracked by default and used to find the gradient, so do use `tape.watch()`*

In [112]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a)+ tf.square(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-0.1684204 -0.5020665]
 [ 0.9471321  0.5898169]], shape=(2, 2), dtype=float32)


### **You can GradientTapefind higher order derivatives by opening a few more:**

In [113]:
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))

# differentiation of c w.r.t a
    dc_da = tape.gradient(c,a) #first differentiation

# differentiation of dc_da w.r.t a
  d2c_d2a = outer_tape.gradient(dc_da, a) # second differentiation
  print(d2c_d2a)

tf.Tensor(
[[0.57568985 0.7655419 ]
 [0.12753117 0.9209411 ]], shape=(2, 2), dtype=float32)
